[build]
  command = "npm run build"
  publish = "dist"

# Proxy API calls to backend
[[redirects]]
  from = "/api/*"
  to = "https://api-growtechafrica.blacksillicon.com/api/:splat"
  status = 200
